### ISSUE TITLE
Cannot add more than 1 additional node due to "This JMX port is already in use."

### ISSUE THREAD

**Issue by Bouncheck** [scylladb/scylla-ccm#641]
After creating a cluster, when adding new nodes sequentially the ccm throws an error about JMX port in use on second `ccm add`.
I'm assuming it should pick non-conflicting jmx ports if they are not specified explicitly (even though 6.2.3 does not really need them IIRC).
```
[wo@fedora tmp]$ mkdir ccmtest
[wo@fedora tmp]$ ccm create ccm_1 -i 127.0.2. -n 1:0 -v release:6.2.3 --scylla --config-dir=/tmp/ccmtest
Current cluster is now: ccm_1
[wo@fedora tmp]$ ccm add -i 127.0.2.2 -d dc1 node2 --scylla --config-dir=/tmp/ccmtest
[wo@fedora tmp]$ ccm add -i 127.0.2.3 -d dc1 node3 --scylla --config-dir=/tmp/ccmtest
This JMX port is already in use. Choose another.
Usage: ccm add [options] node_name

Add a new node to the current cluster

Options:
  -h, --help            show this help message and exit

[...]
```
After that node.conf files have the following contents:
node1 conf:
```
name: node1
status: UNINITIALIZED
auto_bootstrap: false
interfaces:
  storage:
  - 127.0.2.1
  - 7000
  binary:
  - 127.0.2.1
  - 9042
jmx_port: '7199'
config_options: {}
initial_token: -9223372036854775808
remote_debug_port: '0'
data_center: dc1
```

node2 conf:
```
name: node2
status: UNINITIALIZED
auto_bootstrap: false
interfaces:
  storage:
  - 127.0.2.2
  - 7000
  binary:
  - 127.0.2.2
  - 9042
jmx_port: 7199
config_options: {}
remote_debug_port: '2000'
data_center: dc1
```
Note that one node has `'7199'` while other has `7199` port. Probably not of much significance but it's easy to miss.
node3 does not exist.
The results are the same if i try starting the nodes in between the adds (ccm create -> ccm start -> ccm add node2 -> ccm start node2 -> ccm add node 3)
